### DISCUSSION TITLE
Does anyone have instructions on how to run this behind a reverse proxy?

### DISCUSSION THREAD

**Discussion by ovizii** [bluet/docker-cronicle-docker#33] [Q&A] [answered]
Security aside, I'm able to do it but still trying to figure out how these variables should be set if accessing it from the outside via a reverse proxy:

CRONICLE_server_comm_use_hostnames
CRONICLE_web_socket_use_hostnames
CRONICLE_base_app_url
--hostname

I assume the first two need to be true, not sure about the base URL, should it simply be i.e. https://cronicle.domain.tld since the reverse proxy provides the SSL certificate and redirects to port 3012 of cronicle?

That seemed to work at first, but I couldn't get cronicle to properly connect via websocket for live job viewing.

I'm using traefik as reverse proxy, happy to show you my docker-compose.yml so far, open for any tips.

**Comment by ovizii** [comment, marked as answer]
I got it working behind traefik as reverse proxy with this docker-compose.yml

```
version: '3.9'

services:

# https://github.com/bluet/docker-cronicle-docker
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    hostname: cronicle
    environment:
      - TZ=Europe/Berlin
      - HOSTNAME=cronicle.mydomain.tld
      - CRONICLE_secret_key=supersecretkey
      - CRONICLE_base_app_url=https://cronicle.mydomain.tld
      - CRONICLE_web_socket_use_hostnames=1
      - CRONICLE_server_comm_use_hostnames=1
      - CRONICLE_email_from=me@mydomain.tld
      - CRONICLE_smtp_hostname=10.10.10.10
      - CRONICLE_port=25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/opt/cronicle/data
      - ./logs:/opt/cronicle/logs
      - ./plugins:/opt/cronicle/plugins
      - ./app:/app
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.cronicle.tls=true"
      - "traefik.http.routers.cronicle.entrypoints=websecure"
      - "traefik.http.routers.cronicle.rule=Host(`cronicle.mydomain.tld`)"
      - "traefik.http.routers.cronicle.middlewares=secHeaders@file,localIPsOnly@file"
      - "traefik.http.routers.cronicle.service=cronicle"
      - "traefik.http.services.cronicle.loadbalancer.server.port=3012"
      - "traefik.http.services.cronicle.loadbalancer.server.scheme=http"
    networks:
      - traefik

networks:
  traefik:
    external: true

```
