### ISSUE TITLE
Waiting for master server in the last update

### ISSUE THREAD

**Issue by rupertgti** [bluet/docker-cronicle-docker#49]
I had my docker cronicle instance worked perfectly but I applied the last update and is still in this state for 1 hour, I restarted the docker container several times....

I read something about this:
https://github.com/jhuckaby/Cronicle/issues/805
https://github.com/jhuckaby/Cronicle/wiki/Troubleshooting

I use this docker compose always:

```
# https://github.com/bluet/docker-cronicle-docker/blob/master/README.md
version: '3.8'
services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    hostname: cronicle
    environment:
      - TZ=Europe/Madrid
      - UID=1000
      - GID=1000
      # - CRONICLE_base_app_url=http://cronicle/
    ports:
      - "3012:3012"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/log:/dev/log
      - /home/12345/docker/cronicle/data:/opt/cronicle/data
      - /home/12345/docker/cronicle/logs:/opt/cronicle/logs
      - /home/12345/docker/cronicle/plugins:/opt/cronicle/plugins
      - /home/12345/docker/cronicle/workloads/app:/app
    restart: unless-stopped
```

and entering in the doker bash:

```
docker exec -it 2fb865189467 bash
2fb865189467:/opt/cronicle# node -e 'console.log(require("os").hostname().toLowerCase());'
2fb865189467
```

I think all have a good configuration, any ideas?
