### ISSUE TITLE
Document hostname option in docker

### ISSUE THREAD

**Issue by ngosang** [bluet/docker-cronicle-docker#7]
In Docker the hostname is random unless you set it. After restarting Cronicle I experienced this issue => https://github.com/jhuckaby/Cronicle/issues/36

You should update the "docker run" command to include `-h local-docker`. Maybe you want to include a reference docker-compose too.

My docker-compose.yml

```
version: '3.8'
services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    hostname: local-docker
    environment:
      - TZ=Europe/Madrid
      # - CRONICLE_base_app_url=http://cronicle.home/
    ports:
      - "3012:3012"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/cronicle_volume/data:/opt/cronicle/data
      - /root/docker/cronicle_volume/logs:/opt/cronicle/logs
      - /root/docker/cronicle_volume/plugins:/opt/cronicle/plugins
      - /root/docker/cronicle_volume/app:/app
    restart: unless-stopped
```
